name: Deploy

on:
 push:
   branches: [master]
 pull_request:
   branches: [master]

permissions:
  contents: read

jobs:
 deploy-app:
   runs-on: ubuntu-20.04
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Deploy the app
       uses: digitalocean/app_action/deploy@v2
       with:
         token: ${{ secrets.GREENLIGHT_PRODUCTION }} 
